/**
 * Embed customer-authored runtime inputs into generated TypeScript modules.
 *
 * Cloudflare Workers has no project checkout at request time. The generated
 * map preserves the existing source-of-truth files while making them available
 * through the Worker bundle. It is rebuilt before dev/build and after install;
 * generated output is ignored so authors continue editing only the source.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import path from 'node:path'
import { compile } from '@mdx-js/mdx'
// tsx exposes these extensionless TypeScript modules through CJS interop when
// this generator runs as ESM. Their declared shape still has named exports.
// @ts-expect-error -- runtime interop intentionally provides the default object
import frontmatterModule from '../src/lib/frontmatter'
// @ts-expect-error -- runtime interop intentionally provides the default object
import rehypeModule from '../src/mdx/rehype'
// @ts-expect-error -- runtime interop intentionally provides the default object
import remarkModule from '../src/mdx/remark'

const { parseFrontmatter } = frontmatterModule as unknown as typeof import('../src/lib/frontmatter')
const { rehypePlugins } = rehypeModule as unknown as typeof import('../src/mdx/rehype')
const { remarkPlugins } = remarkModule as unknown as typeof import('../src/mdx/remark')

interface RuntimeSourceEntry {
  content: string
  modifiedAtMs: number
}

const projectRoot = process.cwd()
const outputPath = path.join(projectRoot, 'src/generated/runtime-sources.ts')
const compiledDocsDirectory = path.join(projectRoot, 'src/generated/runtime-docs')
const compiledDocsIndexPath = path.join(projectRoot, 'src/generated/runtime-docs.ts')
const sources: Record<string, RuntimeSourceEntry> = {}

function projectPath(filePath: string): string {
  return path.relative(projectRoot, filePath).split(path.sep).join('/')
}

function addTextFile(filePath: string): void {
  if (!existsSync(filePath)) return
  const stats = statSync(filePath)
  if (!stats.isFile()) return
  sources[projectPath(filePath)] = {
    content: readFileSync(filePath, 'utf8'),
    modifiedAtMs: stats.mtimeMs,
  }
}

function walkTextFiles(directory: string, extensions: ReadonlyArray<string>): void {
  if (!existsSync(directory)) return
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const filePath = path.join(directory, entry.name)
    if (entry.isDirectory()) walkTextFiles(filePath, extensions)
    else if (entry.isFile() && extensions.some((extension) => entry.name.endsWith(extension))) {
      addTextFile(filePath)
    }
  }
}

walkTextFiles(path.join(projectRoot, 'src/content'), ['.mdx', '.md'])
walkTextFiles(path.join(projectRoot, 'snippets'), ['.mdx', '.md'])
// URL-style OpenAPI paths resolve from public/. Embed only spec-shaped text
// files rather than the entire asset tree, which may contain large binaries.
walkTextFiles(path.join(projectRoot, 'public'), ['.yaml', '.yml', '.json'])
addTextFile(path.join(projectRoot, 'openapi.yaml'))
addTextFile(path.join(projectRoot, 'openapi.yml'))
addTextFile(path.join(projectRoot, 'openapi.json'))
addTextFile(path.join(projectRoot, 'AGENTS.md'))

mkdirSync(path.dirname(outputPath), { recursive: true })
writeFileSync(
  outputPath,
  `/** Generated by scripts/build-runtime-sources.mts. Do not edit. */\n` +
    `export interface RuntimeSourceEntry { content: string; modifiedAtMs: number }\n` +
    `export const runtimeSources: Readonly<Record<string, RuntimeSourceEntry>> = ${JSON.stringify(
      sources,
    )}\n`,
  'utf8',
)

const snippetImportPattern = /^\s*import\s+\{([^}]+)\}\s+from\s+['"]\/snippets\/[^'"]+['"];?\s*$/gm

/**
 * Compile MDX while the build still has Node privileges.
 *
 * next-mdx-remote evaluates generated JavaScript with `new Function` at request
 * time. Workerd intentionally disallows that. Static generated modules retain
 * the same remark/rehype pipeline and component injection contract without an
 * unsafe-eval binding in production.
 */
async function writeCompiledDocs(): Promise<number> {
  rmSync(compiledDocsDirectory, { recursive: true, force: true })
  mkdirSync(compiledDocsDirectory, { recursive: true })

  const imports: Array<string> = []
  const records: Array<string> = []
  const mdxSources = Object.entries(sources).filter(([filePath]) => filePath.endsWith('.mdx'))

  for (const [filePath, entry] of mdxSources) {
    const index = records.length
    const moduleName = `RuntimeDoc${index}`
    const frontmatterName = `RuntimeFrontmatter${index}`
    const modulePath = path.join(compiledDocsDirectory, `doc-${index}.tsx`)
    const parsed = parseFrontmatter(entry.content)
    const mdxSource = parsed.content.replace(snippetImportPattern, '')
    let program
    try {
      program = await compile(mdxSource, {
        outputFormat: 'program',
        remarkPlugins,
        rehypePlugins,
      })
    } catch (error) {
      throw new Error(
        `Failed to compile runtime MDX ${filePath}: ${error instanceof Error ? error.message : String(error)}`,
        { cause: error },
      )
    }

    writeFileSync(
      modulePath,
      `// @ts-nocheck -- generated MDX program\n${String(program)}\n` +
        `export const frontmatter = ${JSON.stringify(parsed.data)} as const\n`,
      'utf8',
    )
    imports.push(
      `import ${moduleName}, { frontmatter as ${frontmatterName} } from './runtime-docs/doc-${index}'`,
    )
    records.push(
      `${JSON.stringify(filePath)}: { component: ${moduleName}, frontmatter: ${frontmatterName} }`,
    )
  }

  writeFileSync(
    compiledDocsIndexPath,
    `/** Generated by scripts/build-runtime-sources.mts. Do not edit. */\n` +
      `import type { ComponentType } from 'react'\n` +
      `${imports.join('\n')}\n` +
      `export interface PrecompiledRuntimeDoc {\n` +
      `  component: ComponentType<{ components?: Record<string, unknown> }>\n` +
      `  frontmatter: Readonly<Record<string, unknown>>\n` +
      `}\n` +
      `export const runtimeDocs: Readonly<Record<string, PrecompiledRuntimeDoc>> = {\n` +
      `  ${records.join(',\n  ')}\n` +
      `}\n`,
    'utf8',
  )
  return mdxSources.length
}

async function main(): Promise<void> {
  const compiledDocCount = await writeCompiledDocs()
  console.log(
    `[thally] runtime sources: embedded ${Object.keys(sources).length} file(s), compiled ${compiledDocCount} MDX module(s)`,
  )
}

void main()
